/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mmdeploy_RotatedDetector */

#ifndef _Included_mmdeploy_RotatedDetector
#define _Included_mmdeploy_RotatedDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mmdeploy_RotatedDetector
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_mmdeploy_RotatedDetector_create(JNIEnv *, jobject, jstring, jstring,
                                                             jint);

/*
 * Class:     mmdeploy_RotatedDetector
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mmdeploy_RotatedDetector_destroy(JNIEnv *, jobject, jlong);

/*
 * Class:     mmdeploy_RotatedDetector
 * Method:    apply
 * Signature: (J[Lmmdeploy/Mat;[I)[Lmmdeploy/RotatedDetector/Result;
 */
JNIEXPORT jobjectArray JNICALL Java_mmdeploy_RotatedDetector_apply(JNIEnv *, jobject, jlong,
                                                                   jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
