pipeline {
    agent { label 'deploy_linux_3090' }
    parameters {
        choice(
            name: 'CONFIG',
            choices : [
                'default.config',
                'default_2080.config',
                'openmmlabv1_quicktest.config',
                'openmmlabv1_quicktest.config',
                'openmmlabv2_quicktest.config',
                'win_default.config'
            ],
            description: 'select config'
        )
        choice(
            name: 'EXEC_NODE',
            choices: [
                'deploy_linux_3090',
                'deploy_linux_2080'
            ],
            description: 'select exec_node'
        )
        booleanParam(
            name: 'EXEC_BUILD',
            defaultValue: true,
        )
        booleanParam(
            name: 'EXEC_PREBUILD',
            defaultValue: true,
        )
        booleanParam(
            name: 'EXEC_CONVERT',
            defaultValue: true,
        )
        booleanParam(
            name: 'EXEC_UNITTEST',
            defaultValue: true,
        )
        string(
            name: 'codebase_list',
            defaultValue: 'mmcls mmdet mmedit mmseg mmpose mmocr mmdet3d mmaction'
        )
        string(
            name: 'exec_performance',
            defaultValue: 'y'
        )
        string(
            name: 'exec_torch_versions',
            defaultValue: '1.10.0'
        )
        string(
            name: 'exec_models',
            defaultValue: 'all'
        )
        string(
            name: 'exec_backends',
            defaultValue: 'onnxruntime tensorrt ncnn torchscript openvino'
        )
        string(
            name: 'max_job_nums',
            defaultValue: '3'
        )
        string(
            name: 'repo_url',
            defaultValue: 'https://github.com/open-mmlab/mmdeploy.git'
        )
        string(
            name: 'mmdeploy_branch',
            defaultValue: 'master'
        )
        string(
            name: 'repo_version',
            defaultValue: 'v1.0'
        )
        string(
            name: 'tensorrt_version',
            defaultValue: '8.2.5.1'
        )
        string(
            name: 'requirement',
            defaultValue: 'requirementV1.0.json'
        )
    }

    stages {
        stage('Regression') {
            stage('Set Config') {
                agent { label 'deploy_linux' }
                steps {
                    sh "cp tests/jenkins/conf/${params.CONFIG} tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/codebase_list=.*/codebase_list=${params.codebase_list}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/exec_performance=.*/exec_performance=${params.exec_performance}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/exec_torch_versions=.*/exec_torch_versions=${params.exec_torch_versions}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/exec_models=.*/exec_models=${params.exec_models}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/exec_backends=.*/exec_backends=${params.exec_backends}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/max_job_nums=.*/max_job_nums=${params.max_job_nums}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/repo_url=.*/repo_url=${params.repo_url}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/mmdeploy_branch=.*/mmdeploy_branch=${params.mmdeploy_branch}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/repo_version=.*/repo_version=${params.repo_version}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/tensorrt_version=.*/tensorrt_version=${params.tensorrt_version}/g' tests/jenkins/conf/tmp.config"
                    sh "sed -i 's/requirement=.*/requirement=${params.requirement}/g' tests/jenkins/conf/tmp.config"
                }
            }
            parallel {
                stage('Build') {
                    agent { label params.EXEC_NODE }
                    when {
                        expression { return params.EXEC_BUILD }
                    }
                    steps {
                        sh "tests/jenkins/scripts/test_build.sh 'tmp.config'"
                    }
                }

                stage('Convert') {
                    agent { label params.EXEC_NODE }
                    when {
                        expression { return params.EXEC_CONVERT }
                    }
                    steps {
                        sh "tests/jenkins/scripts/test_convert.sh 'tmp.config'"
                    }
                }

                stage('Prebuild') {
                    agent { label params.EXEC_NODE }
                    when {
                        expression { return params.EXEC_PREBUILD }
                    }
                    steps {
                        sh "tests/jenkins/scripts/test_prebuild.sh 'tmp.config'"
                    }
                }

                stage('Unittest') {
                    agent { label params.EXEC_NODE }
                    when {
                        expression { return params.EXEC_UNITTEST }
                    }
                    steps {
                        sh "tests/jenkins/scripts/test_ut.sh 'tmp.config'"
                    }
                }
            }
        }
        stage('Tear Down') {
            agent { label params.EXEC_NODE }
            steps {
                sh "rm -f tests/jenkins/conf/tmp.config"
            }
        }
    }
}
