# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x08mmdeploy\"7\n\x08PPLModel\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07weights\x18\x02 \x01(\x0c\x42\x07\n\x05_name\"H\n\tNCNNModel\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06params\x18\x02 \x01(\x0c\x12\x0f\n\x07weights\x18\x03 \x01(\x0c\x42\x07\n\x05_name\"\x89\x01\n\x05Model\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.mmdeploy.ModelType\x12&\n\x04ncnn\x18\x02 \x01(\x0b\x32\x13.mmdeploy.NCNNModelH\x00\x88\x01\x01\x12$\n\x03ppl\x18\x03 \x01(\x0b\x32\x12.mmdeploy.PPLModelH\x01\x88\x01\x01\x42\x07\n\x05_ncnnB\x06\n\x04_ppl\"\x07\n\x05\x45mpty\"Q\n\x06Tensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\x05\x64type\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\r\n\x05shape\x18\x04 \x03(\x05\x42\x08\n\x06_dtype\",\n\nTensorList\x12\x1e\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x10.mmdeploy.Tensor\"E\n\x05Reply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04info\x18\x02 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x10.mmdeploy.Tensor\"\x16\n\x05Names\x12\r\n\x05names\x18\x01 \x03(\t*,\n\tModelType\x12\n\n\x06UNKOWN\x10\x00\x12\x08\n\x04NCNN\x10\x01\x12\t\n\x05PPLNN\x10\x02\x32\xcf\x01\n\tInference\x12*\n\x04Init\x12\x0f.mmdeploy.Model\x1a\x0f.mmdeploy.Reply\"\x00\x12\x31\n\x0bOutputNames\x12\x0f.mmdeploy.Empty\x1a\x0f.mmdeploy.Names\"\x00\x12\x34\n\tInference\x12\x14.mmdeploy.TensorList\x1a\x0f.mmdeploy.Reply\"\x00\x12-\n\x07\x44\x65stroy\x12\x0f.mmdeploy.Empty\x1a\x0f.mmdeploy.Reply\"\x00\x42(\n\x0emmdeploy.riscvB\x0cRISCVWrapperP\x01\xa2\x02\x05RISCVb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n\016mmdeploy.riscvB\014RISCVWrapperP\001\242\002\005RISCV'
    _MODELTYPE._serialized_start = 533
    _MODELTYPE._serialized_end = 577
    _PPLMODEL._serialized_start = 29
    _PPLMODEL._serialized_end = 84
    _NCNNMODEL._serialized_start = 86
    _NCNNMODEL._serialized_end = 158
    _MODEL._serialized_start = 161
    _MODEL._serialized_end = 298
    _EMPTY._serialized_start = 300
    _EMPTY._serialized_end = 307
    _TENSOR._serialized_start = 309
    _TENSOR._serialized_end = 390
    _TENSORLIST._serialized_start = 392
    _TENSORLIST._serialized_end = 436
    _REPLY._serialized_start = 438
    _REPLY._serialized_end = 507
    _NAMES._serialized_start = 509
    _NAMES._serialized_end = 531
    _INFERENCE._serialized_start = 580
    _INFERENCE._serialized_end = 787
# @@protoc_insertion_point(module_scope)
