/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mmdeploy_Model */

#ifndef _Included_mmdeploy_Model
#define _Included_mmdeploy_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mmdeploy_Model
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mmdeploy_Model_create(JNIEnv *, jobject, jstring);

/*
 * Class:     mmdeploy_Model
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mmdeploy_Model_destroy(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
