/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mmdeploy_TextRecognizer */

#ifndef _Included_mmdeploy_TextRecognizer
#define _Included_mmdeploy_TextRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mmdeploy_TextRecognizer
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_mmdeploy_TextRecognizer_create(JNIEnv *, jobject, jstring, jstring,
                                                            jint);

/*
 * Class:     mmdeploy_TextRecognizer
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mmdeploy_TextRecognizer_destroy(JNIEnv *, jobject, jlong);

/*
 * Class:     mmdeploy_TextRecognizer
 * Method:    apply
 * Signature: (J[Lmmdeploy/Mat;)[Lmmdeploy/TextRecognizer/Result;
 */
JNIEXPORT jobjectArray JNICALL Java_mmdeploy_TextRecognizer_apply(JNIEnv *, jobject, jlong,
                                                                  jobjectArray);

/*
 * Class:     mmdeploy_TextRecognizer
 * Method:    applyBbox
 * Signature: (J[Lmmdeploy/Mat;[Lmmdeploy/TextDetector/Result;[I)[Lmmdeploy/TextRecognizer/Result;
 */
JNIEXPORT jobjectArray JNICALL Java_mmdeploy_TextRecognizer_applyBbox(JNIEnv *, jobject, jlong,
                                                                      jobjectArray, jobjectArray,
                                                                      jintArray);

#ifdef __cplusplus
}
#endif
#endif
