/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mmdeploy_Detector */

#ifndef _Included_mmdeploy_Detector
#define _Included_mmdeploy_Detector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mmdeploy_Detector
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_mmdeploy_Detector_create(JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     mmdeploy_Detector
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mmdeploy_Detector_destroy(JNIEnv *, jobject, jlong);

/*
 * Class:     mmdeploy_Detector
 * Method:    apply
 * Signature: (J[Lmmdeploy/Mat;[I)[Lmmdeploy/Detector/Result;
 */
JNIEXPORT jobjectArray JNICALL Java_mmdeploy_Detector_apply(JNIEnv *, jobject, jlong, jobjectArray,
                                                            jintArray);

#ifdef __cplusplus
}
#endif
#endif
