/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mmdeploy_Device */

#ifndef _Included_mmdeploy_Device
#define _Included_mmdeploy_Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mmdeploy_Device
 * Method:    create
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_mmdeploy_Device_create(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     mmdeploy_Device
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mmdeploy_Device_destroy(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
