/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mmdeploy_PoseDetector */

#ifndef _Included_mmdeploy_PoseDetector
#define _Included_mmdeploy_PoseDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mmdeploy_PoseDetector
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_mmdeploy_PoseDetector_create(JNIEnv *, jobject, jstring, jstring,
                                                          jint);

/*
 * Class:     mmdeploy_PoseDetector
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mmdeploy_PoseDetector_destroy(JNIEnv *, jobject, jlong);

/*
 * Class:     mmdeploy_PoseDetector
 * Method:    apply
 * Signature: (J[Lmmdeploy/Mat;)[Lmmdeploy/PoseDetector/Result;
 */
JNIEXPORT jobjectArray JNICALL Java_mmdeploy_PoseDetector_apply(JNIEnv *, jobject, jlong,
                                                                jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
